easy_admin:
   entities:       
       - App\Entity\Client
       - App\Entity\Entreprise
       - App\Entity\Network
       - App\Entity\Product
       - App\Entity\ProductLine
       - App\Entity\SocialNetwork
       - App\Entity\Supervisor
       - App\Entity\User
