easy_admin:
    user:
        name_property_path: username
    entities:
        User:
            display_name: true
            name_property_path: username
            class: App\Entity\User
            label: 'User'
            password_encoding: { algorithm: 'bcrypt', cost: 12 }
            list:
                fields:
                    # all users will see the first three columns
                    - username
                    - { property: 'enterprises', label: 'Empresas'} 
                    - { property: 'max', label: 'Nº empresas max'}

            edit:
                fields:
                    # all users will see the first three columns
                    - username
                    - enterprises
                    - { property: 'max', label: 'Nº empresas max'}
                    # - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            new:
                fields: 
                    - username
                    - {property: 'password', type: 'password'}
                    - enterprises
        Client:
            class: App\Entity\Client
            label: 'Cliente'
        Company:
            class: App\Entity\Enterprise
            label: 'Empresa'
        Invoice:
            class: App\Entity\Invoice
            label: 'Factura'
        Supervisor:
            class: App\Entity\Supervisor

